///
/// Code generated by jsonToDartModel https://ashamp.github.io/jsonToDartModel/
///
class LoginDataModelUser {
/*
{
  "id": 1,
  "name": "abcd",
  "phone": "7896541230",
  "age": 32,
  "gender": "male",
  "otp": "7241",
  "auth_token": "8|vVG8UokUH2o3UIE9wwvdB4a2pycYVaYndcjvfxKY2441d622",
  "is_logged_out": "0",
  "is_verified": 1,
  "created_at": "2025-11-20T09:17:19.000000Z",
  "updated_at": "2025-11-20T09:18:00.000000Z"
}
*/

  int? id;
  String? name;
  String? phone;
  int? age;
  String? gender;
  String? otp;
  String? authToken;
  String? isLoggedOut;
  int? isVerified;
  String? createdAt;
  String? updatedAt;

  LoginDataModelUser({
    this.id,
    this.name,
    this.phone,
    this.age,
    this.gender,
    this.otp,
    this.authToken,
    this.isLoggedOut,
    this.isVerified,
    this.createdAt,
    this.updatedAt,
  });
  LoginDataModelUser.fromJson(Map<String, dynamic> json) {
    id = json['id']?.toInt();
    name = json['name']?.toString();
    phone = json['phone']?.toString();
    age = json['age']?.toInt();
    gender = json['gender']?.toString();
    otp = json['otp']?.toString();
    authToken = json['auth_token']?.toString();
    isLoggedOut = json['is_logged_out']?.toString();
    isVerified = json['is_verified']?.toInt();
    createdAt = json['created_at']?.toString();
    updatedAt = json['updated_at']?.toString();
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['phone'] = phone;
    data['age'] = age;
    data['gender'] = gender;
    data['otp'] = otp;
    data['auth_token'] = authToken;
    data['is_logged_out'] = isLoggedOut;
    data['is_verified'] = isVerified;
    data['created_at'] = createdAt;
    data['updated_at'] = updatedAt;
    return data;
  }
}

class LoginDataModel {
/*
{
  "status": "True",
  "message": "Login successfully",
  "user": {
    "id": 1,
    "name": "abcd",
    "phone": "7896541230",
    "age": 32,
    "gender": "male",
    "otp": "7241",
    "auth_token": "8|vVG8UokUH2o3UIE9wwvdB4a2pycYVaYndcjvfxKY2441d622",
    "is_logged_out": "0",
    "is_verified": 1,
    "created_at": "2025-11-20T09:17:19.000000Z",
    "updated_at": "2025-11-20T09:18:00.000000Z"
  }
}
*/

  String? status;
  String? message;
  LoginDataModelUser? user;

  LoginDataModel({
    this.status,
    this.message,
    this.user,
  });
  LoginDataModel.fromJson(Map<String, dynamic> json) {
    status = json['status']?.toString();
    message = json['message']?.toString();
    user = (json['user'] != null) ? LoginDataModelUser.fromJson(json['user']) : null;
  }
  Map<String, dynamic> toJson() {
    final data = <String, dynamic>{};
    data['status'] = status;
    data['message'] = message;
    if (user != null) {
      data['user'] = user!.toJson();
    }
    return data;
  }
}
